version: '3'

dotenv:
  - .env

tasks:
  server:
    cmd: |
      go run server/main.go server/tools.go

  client:
    cmd: |
      DES_KEY=$DES_KEY go run client/main.go client/tools.go

  rsa:
    cmds: 
      - clear
      - go test ./... -v

  fmt:
    cmds:
      - gofmt -s -w server/main.go server/tools.go
      - gofmt -s -w client/main.go client/tools.go
      - gofmt -s -w rsa/generate.go rsa/rsa.go
